### ISSUE TITLE
Exception provisioning containers: SSLHandshakeException: Received fatal alert: bad_certificate bad_certificate

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#133] opened 2015-07-02 11:28 UTC
Built master/HEAD. Ran `./bin/clocker.sh jclouds:softlayer:ams01`. Attempted to deploy riak-counters example (https://raw.githubusercontent.com/csabapalfi/riak-counters-example/master/clocker.yml). Every entity in the Riak application failed at provisioning with this exception:

```
2015-07-02 12:19:12,861 WARN  b.l.jclouds.JcloudsLocation [brooklyn-execmanager-ZIBiVbK0-256]: IOException found...
javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.7.0_51]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.7.0_51]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1959) ~[na:1.7.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077) ~[na:1.7.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) ~[na:1.7.0_51]
    ....
```

The `DockerContainer` children of the host entities are stuck spinning as if they're starting, but the start task failed with:
```
Failed after 3.02s: Error invoking start at DockerContainerImpl{id=PUDU0uTO}: Unable to access cloud JcloudsLocation[docker:https://81.95.144.60:2376:conf/server-cert.pem/docker:https://81.95.144.60:2376@zW8EqnJY] to resolve PortableTemplateBuilder[ports=[22, 8093, 7999, 8099, 8098, 6000, 8087, 8985, 4369], imageId=bacb06d7f62997716eae9d7fb8f5bf925ab6dc6efc000d38edc1214ba5f43f8e, hardwareId=small, imageChooserFunction=brooklyn.location.jclouds.BrooklynImageChooser$ImageChooserFromOrdering@78c9cffa]: org.jclouds.http.HttpResponseException: Received fatal alert: bad_certificate connecting to GET https://81.95.144.60:2376/v1.16/images/json HTTP/1.1

brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=PUDU0uTO}: Unable to access cloud JcloudsLocation[docker:https://81.95.144.60:2376:conf/server-cert.pem/docker:https://81.95.144.60:2376@zW8EqnJY] to resolve PortableTemplateBuilder[ports=[22, 8093, 7999, 8099, 8098, 6000, 8087, 8985, 4369], imageId=bacb06d7f62997716eae9d7fb8f5bf925ab6dc6efc000d38edc1214ba5f43f8e, hardwareId=small, imageChooserFunction=brooklyn.location.jclouds.BrooklynImageChooser$ImageChooserFromOrdering@78c9cffa]: org.jclouds.http.HttpResponseException: Received fatal alert: bad_certificate connecting to GET https://81.95.144.60:2376/v1.16/images/json HTTP/1.1
	at brooklyn.management.internal.EffectorUtils.handleEffectorException(EffectorUtils.java:270)
	at brooklyn.management.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:255)
	at brooklyn.entity.basic.MethodEffector.call(MethodEffector.java:149)
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:57)
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:51)
	at brooklyn.entity.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:83)
	at brooklyn.util.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:337)
	at brooklyn.util.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:469)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to access cloud JcloudsLocation[docker:https://81.95.144.60:2376:conf/server-cert.pem/docker:https://81.95.144.60:2376@zW8EqnJY] to resolve PortableTemplateBuilder[ports=[22, 8093, 7999, 8099, 8098, 6000, 8087, 8985, 4369], imageId=bacb06d7f62997716eae9d7fb8f5bf925ab6dc6efc000d38edc1214ba5f43f8e, hardwareId=small, imageChooserFunction=brooklyn.location.jclouds.BrooklynImageChooser$ImageChooserFromOrdering@78c9cffa]: org.jclouds.http.HttpResponseException: Received fatal alert: bad_certificate connecting to GET https://81.95.144.60:2376/v1.16/images/json HTTP/1.1
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:314)
	at brooklyn.management.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:250)
	... 10 more
Caused by: java.lang.IllegalStateException: Unable to access cloud JcloudsLocation[docker:https://81.95.144.60:2376:conf/server-cert.pem/docker:https://81.95.144.60:2376@zW8EqnJY] to resolve PortableTemplateBuilder[ports=[22, 8093, 7999, 8099, 8098, 6000, 8087, 8985, 4369], imageId=bacb06d7f62997716eae9d7fb8f5bf925ab6dc6efc000d38edc1214ba5f43f8e, hardwareId=small, imageChooserFunction=brooklyn.location.jclouds.BrooklynImageChooser$ImageChooserFromOrdering@78c9cffa]: org.jclouds.http.HttpResponseException: Received fatal alert: bad_certificate connecting to GET https://81.95.144.60:2376/v1.16/images/json HTTP/1.1
	at brooklyn.location.jclouds.JcloudsLocation.buildTemplate(JcloudsLocation.java:1420)
	at brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:660)
	at brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:596)
	at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:453)
	at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:570)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at brooklyn.util.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.groovy:144)
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:286)
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:310)
	... 11 more
Caused by: org.jclouds.http.HttpResponseException: Received fatal alert: bad_certificate connecting to GET https://81.95.144.60:2376/v1.16/images/json HTTP/1.1
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:117)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy193.listImages(Unknown Source)
	at org.jclouds.docker.compute.strategy.DockerComputeServiceAdapter.listImages(DockerComputeServiceAdapter.java:183)
	at org.jclouds.docker.compute.strategy.DockerComputeServiceAdapter.listImages(DockerComputeServiceAdapter.java:63)
	at org.jclouds.compute.config.ComputeServiceAdapterContextModule$2.get(ComputeServiceAdapterContextModule.java:121)
	at org.jclouds.compute.config.ComputeServiceAdapterContextModule$2.get(ComputeServiceAdapterContextModule.java:118)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
	at org.jclouds.compute.suppliers.ImageCacheSupplier.get(ImageCacheSupplier.java:64)
	at org.jclouds.compute.domain.internal.TemplateBuilderImpl.getImages(TemplateBuilderImpl.java:881)
	at org.jclouds.compute.domain.internal.TemplateBuilderImpl.build(TemplateBuilderImpl.java:681)
	at brooklyn.location.jclouds.templates.PortableTemplateBuilder.newJcloudsTemplate(PortableTemplateBuilder.java:70)
	at brooklyn.location.jclouds.templates.PortableTemplateBuilder.build(PortableTemplateBuilder.java:48)
	at brooklyn.location.jclouds.JcloudsLocation.buildTemplate(JcloudsLocation.java:1398)
	... 27 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1959)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:241)
	at com.squareup.okhttp.Connection.connect(Connection.java:158)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
	at com.squareup.okhttp.Call.getResponse(Call.java:262)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at org.jclouds.http.okhttp.OkHttpCommandExecutorService.invoke(OkHttpCommandExecutorService.java:145)
	at org.jclouds.http.okhttp.OkHttpCommandExecutorService.invoke(OkHttpCommandExecutorService.java:58)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:96)
	... 53 more
```

The Weave containers in each of the Docker hosts appear to be running normally.

**Comment by grkvlt** [comment] 2015-07-02 14:38
Caused by Docker 1.7.0 needing CA certificate and jclouds was not set up to trust these. I have a patch that should sort this, will reference this issue when creating a PR.

**Comment by csabapalfi** [comment] 2015-07-02 15:49
Maybe we can just set `--tlsverify=false` for now to keep master working and fix this on a branch. What do you think?

**Comment by csabapalfi** [comment] 2015-07-20 15:04
See #136 for the fix.

**Comment by grkvlt** [comment] 2015-08-26 02:07
@sjcorbett closing as fixed in 1.x with recent TLS updates

**Closed by grkvlt** 2015-08-26 02:07 UTC
