### ISSUE TITLE
Cannot run containers when Clocker is running in the same AWS region as DockerHost

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#215] opened 2015-12-07 17:37 UTC
Clocker cannot provision containers when both Clocker and the target DockerHost are running in the same AWS region. I believe that either the AWS security group configuration is incorrect or jclouds should use the host's public IP address rather than hostname.

Clocker configures a security group for the host to allow access to port 2376 from Clocker's public IP address.

When the host is running in the same region Clocker cannot provision containers:

```
Error invoking start at DockerContainerImpl{id=XRko6lFz}: 
java.lang.IllegalStateException: Unable to access cloud JcloudsLocation[docker:https://ec2-52-90-188-72.compute-1.amazonaws.com:2376:/tmp/NU6GolnO-cert.pem/docker:https://ec2-52-90-188-72.compute-1.amazonaws.com:2376@yi4BGSLy] to resolve PortableTemplateBuilder[ports=[9200, 22], imageId=df78b0304a9528cb40e39262602d9217771c0ea2a4cdd489b15c73c9b31085fd, hardwareId=small, imageChooserFunction=org.apache.brooklyn.location.jclouds.BrooklynImageChooser$ImageChooserFromOrdering@6ec08f07]: 
org.jclouds.http.HttpResponseException: Connection timed out connecting to GET https://ec2-52-90-188-72.compute-1.amazonaws.com:2376/v1.16/images/json HTTP/1.1
```

Running a few tests from Clocker to such a host:
* curl dockerHost-hostname:2376 (ec2-..amazonaws.com) times out
* curl dockerHost-publicIp:2376 succeeds
* curl dockerHost-privateIp:2376 times out.
* curl dockerHost-privateIp:2376 succeeds when I change the security group entry to allow 2376 from privateIp/32.

Within AWS hostnames resolve to private IP addresses. At a guess the `GET ec2-52-90-188-72.compute-1.amazonaws.com` is forbidden because port 2376 is only exposed to Clocker's public IP address.

**Comment by grkvlt** [comment] 2015-12-07 17:40
This is a duplicate of #134

**Comment by grkvlt** [comment] 2015-12-07 17:41
@sjcorbett did you try the fix I suggested in the previous issue?

**Comment by sjcorbett** [comment] 2015-12-07 17:46
Yes. Prioritising a fix would be helpful so that others don't have to waste their time working this out again. I appreciate I should have read through the existing issues.

**Closed** 2016-04-27 02:11 UTC
