### ISSUE TITLE
Clocker throws NoSuchMethodError

### ISSUE THREAD

**Issue by RobertDiebels** [brooklyncentral/clocker#430] opened 2017-06-29 08:02 UTC
Hi guys,

I'm getting an Error when running Brooklyn with clocker blueprints.
I followed your getting started guide: http://www.clocker.io/tutorials/getting-started.html
And everything works fine up until the moment I want to add a kubernetes application.

**Steps**

1. Install Brooklyn for windows according to guide.
2. Add clocker according to guide.
3. Launch Brooklyn in persistent mode
4. Specify persistDir in a different drive than your Brooklyn install.
5. Add location according to clocker guide
6. Add kubernetes application
7. Click deploy

**Error**
This is the Error I get from Brooklyn: NoSuchMethodError: org.apache.brooklyn.core.feed.ConfigToAttributes.apply(Lorg/apache/brooklyn/api/entity/EntityLocal;Lorg/apache/brooklyn/core/sensor/AttributeSensorAndConfigKey;)Ljava/lang/Object;

**Versions**
Brooklyn:   0.11
Windows:  10
Clocker:     ?? (Downloaded jars from guide.)

**Comment by duncangrant** [comment] 2017-06-29 11:04
Thanks @RobertDiebels for pointing this out.  As you probably expected we just need to update the docs to point at the latest versions of some of these items to get clocker running on latest Apache brooklyn.  I should probably do a bit of a run through of all the docs to catch all of these issues but I don't want to hold you up so if you want to work round this you would need to do a couple of things:

1. Use latest brooklyn-etcd - downloadable here: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.brooklyn.etcd&a=brooklyn-etcd&v=2.5.0-SNAPSHOT

2. Use an updated clocker.bom with the following lines:
```
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.etcd.brooklyn-etcd:etcd/catalog.bom
    - classpath://io.brooklyn.clocker.common:common/common.bom
    - classpath://io.brooklyn.clocker.common:common/ca.bom
    - classpath://io.brooklyn.clocker.common:docker/docker.bom
    - classpath://io.brooklyn.clocker.common:main/catalog.bom
    - classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/plugins.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/kubernetes.bom

```

I

**Comment by duncangrant** [comment] 2017-06-29 12:50
PRs to fix the above:
https://github.com/brooklyncentral/clocker/pull/431
https://github.com/brooklyncentral/clocker/pull/432

**Comment by RobertDiebels** [comment] 2017-06-29 12:51
@duncangrant Hi, duncan thanks for the response.

I've already done as you suggested. I used the latest jars listed in your Maven repos:
[](https://mvnrepository.com/artifact/io.brooklyn.clocker/clocker-common)
[](https://mvnrepository.com/artifact/io.brooklyn.clocker/clocker-kubernetes)
[](https://mvnrepository.com/artifact/io.brooklyn.etcd/brooklyn-etcd)

The common jar doesn't have a in a main folder. Do I need it? Because I'm getting an error on it when I try to add it to the catalog: [using this version](https://mvnrepository.com/artifact/io.brooklyn.clocker/clocker-common/2.1.0-20170623.1921)

**Comment by duncangrant** [comment] 2017-06-29 12:57
@RobertDiebels yes you do need common.  I'd recommend sticking with the latest release version of those jars rather than the latest snapshots purely from a point of stability.  These should all be the same apart from the brooklyn-etcd jar should be version 2.4.0.

Having said that the snapshot versions get tested nightly so I'd be surprised if they weren't working.
What error did you get?

**Comment by RobertDiebels** [comment] 2017-06-29 13:01
@duncangrant Well I resolved the error by pointing to the `catalog.bom` in clocker-common's `common` folder.  Since the jar doesn't contain a main folder. Though I should note that I'm using the latest version of clocker common as well.
I don't recall the exact error message sorry.

I will revert to the suggested versions and try again with the catalog you suggested.

**Comment by RobertDiebels** [comment] 2017-06-29 13:20
For clarity's sake.
I'm using now using these versions:
```
brooklyn:                  0.11
clocker-kubernetes: 2.1.0-20170623.1921
clocker-common:     2.1.0-20170623.1921
brooklyn-etcd:         2.4.0
locker-swarm:          2.1.0-20170623.1921
```
With this catalog:
```
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.etcd.brooklyn-etcd:etcd/catalog.bom
    - classpath://io.brooklyn.clocker.common:common/common.bom
    - classpath://io.brooklyn.clocker.common:common/ca.bom
    - classpath://io.brooklyn.clocker.common:docker/docker.bom
    - classpath://io.brooklyn.clocker.common:common/catalog.bom <- this line previously broke Brooklyn so I changed it
    - classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/plugins.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/kubernetes.bom
```
The console is now showing me this error: 
`ERROR Error loading catalog item 'org.apache.brooklyn.core.catalog.internal.CatalogItemDo[CatalogEntityItemDto[kubernetes-cluster-application:2.1.0-20170623.1921/Kubernetes Cluster]]': Transformer for Brooklyn OASIS CAMP interpreter gave an error creating this plan: Transformer for catalog gave an error creating this plan: Unable to instantiate kubernetes-cluster; 2 errors including: Error in definition of kubernetes-cluster:2.1.0-20170623.1921: Unable to create spec for type calico-policy-controller-pod. No resolver knew how to handle it. Using resolvers: class org.apache.brooklyn.camp.brooklyn.spi.creation.service.CampServiceSpecResolver[[org.apache.brooklyn.core.resolve.entity.CatalogEntitySpecResolver@c8ff1f6, org.apache.brooklyn.core.resolve.entity.JavaEntitySpecResolver@507efc7a, org.apache.brooklyn.entity.resolve.ChefEntitySpecResolver@758e649b, org.apache.brooklyn.entity.resolve.HardcodedCatalogEntitySpecResolver@4daabb28, org.apache.brooklyn.camp.brooklyn.spi.creation.service.UrlServiceSpecResolver@3e59e32a]]`

Brooklyn shows an error and the kubernetes cluster is now not showing as a possible application.

**Comment by duncangrant** [comment] 2017-06-29 13:39
@RobertDiebels I think you could add the line:
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/pods.bom

It might need to go between 
- classpath://io.brooklyn.clocker.kubernetes:kubernetes/plugins.bom
- classpath://io.brooklyn.clocker.kubernetes:kubernetes/kubernetes.bom

But you'll probably find that the following works:
```
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.clocker.swarm:swarm/catalog.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/catalog.bom
```
In the future we should be able to stop doing all this and just use [clocker.bom](https://github.com/brooklyncentral/clocker/blob/master/clocker.bom) but I'm not sure whether this works using classic brooklyn (we're moving to a karaf based version soon)

**Comment by RobertDiebels** [comment] 2017-06-29 14:05
@duncangrant your last suggestion fixed all my errors.

I removed all the application templates I had then added your suggestion:
```
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.clocker.swarm:swarm/catalog.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/catalog.bom
```
To the catalog and it worked.

Still on the same versions:

```
brooklyn:                  0.11
clocker-kubernetes: 2.1.0-20170623.1921
clocker-common:     2.1.0-20170623.1921
brooklyn-etcd:         2.4.0
locker-swarm:          2.1.0-20170623.1921
```

However now I'm getting errors from AWS stating:

```
Required entities not healthy: VanillaSoftwareProcessImpl{id=n17saqu192}, EtcdClusterImpl{id=pe784fuchj}, BasicStartableImpl{id=s9pwb8cu3p}
Failure running task start (E3leTFqu): ProblemStartingChildrenException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: 3 of 3 parallel child tasks failed; 3 errors including: Error invoking start at VanillaSoftwareProcessImpl{id=n17saqu192}: Failed to get VM after 2 attempts. - First cause is org.jclouds.rest.AuthorizationException: POST https://ec2.eu-central-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized (listed in primary trace); plus 1 more (e.g. the last is org.jclouds.rest.AuthorizationException: POST https://ec2.eu-central-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized): AuthorizationException: POST https://ec2.eu-central-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized
```

I triple checked this as I've gotten this error mupltiple times today. I've created a Brooklyn user with FullAccess to S3, EC2 etc. In fact I even gave it Admin rights. So it can do everything.

I checked this by using a different template, the Python Web Server one and it launched successfully.
Any ideas what might cause this?

**Comment by duncangrant** [comment] 2017-06-29 14:17
@RobertDiebels I think this is possibly an AWS config issue.  Would you mind jumping over to the brooklyn mailing list (or irc if you'd prefer) where there are a few more people who will be able to help. 
https://lists.apache.org/list.html?dev@brooklyn.apache.org
http://webchat.freenode.net/?channels=brooklyncentral

**Comment by neykov** [comment] 2017-06-29 14:19
@RobertDiebels the 401 is probably caused by the specific image used for the machines. It requires accepting its TOC before used for the first time. See [the troubleshooting section](http://www.clocker.io/docs/troubleshooting.html#aws-401-errors) for more details.

**Comment by duncangrant** [comment] 2017-06-29 14:28
@neykov thanks I forgotten about that

**Comment by RobertDiebels** [comment] 2017-06-29 14:48
@neykov Ugh.. It's even written in the comments of the aws-location yaml-file. Thank you! I can see that the ca-server and the etcd-cluster have spawned now. Thanks so much guys :D !

**For future readers:**

Using this catalog:
```
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.clocker.swarm:swarm/catalog.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/catalog.bom
```

On these versions:

```
brooklyn:                  0.11
clocker-kubernetes: 2.1.0-20170623.1921
clocker-common:     2.1.0-20170623.1921
brooklyn-etcd:         2.4.0
locker-swarm:          2.1.0-20170623.1921
```
With the default locations, works like a charm.

Thanks for the help guys, much appreciated! @duncangrant @neykov

**Closed** 2017-06-29 14:49 UTC
